# Generated by Django 5.2.8 on 2025-11-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=100)),
                ('pan_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('employee_type', models.CharField(max_length=50)),
                ('current_city', models.CharField(max_length=100)),
                ('current_pincode', models.CharField(max_length=10)),
                ('loan_for', models.CharField(max_length=100)),
            ],
        ),
    ]
