# Generated by Django 5.2.8 on 2025-11-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_enquiry_created_at_enquiry_net_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpincode',
            name='loan_types',
            field=models.CharField(choices=[('PL', 'Personal Loan'), ('BL', 'Business Loan'), ('BOTH', 'Both')], default='BOTH', max_length=10),
        ),
    ]
