# Generated by Django 5.2.8 on 2025-11-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_bankpincode_loan_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='companyName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='departmentName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='designationName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
