# Generated by Django 5.2.8 on 2025-11-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_enquiry_companyname_enquiry_departmentname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.IntegerField()),
                ('enquiry_id', models.IntegerField()),
                ('process_by', models.CharField(choices=[('good_debt', 'Good Debt'), ('bank', 'Bank')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bank_interest',
            },
        ),
    ]
