# Generated by Django 5.2.8 on 2025-11-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_bankinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='designation',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
